---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: buluma.bootstrap
    - role: buluma.python_pip
    - role: buluma.apache
    - role: buluma.ca_certificates
    - role: buluma.openssl
